<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('product_images')->insert(['id' => 1,'image_url' => 'http://127.0.0.1:8000/uploads/products/product-item1.jpg', 'name' => 'product-item1.jpg','type' => 'jpg','size' => '2222','product_id' => 1,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 2,'image_url' => 'http://127.0.0.1:8000/uploads/products/product-item2.jpg', 'name' => 'product-item2.jpg','type' => 'jpg','size' => '2222','product_id' => 2,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 3,'image_url' => 'http://127.0.0.1:8000/uploads/products/product-item3.jpg', 'name' => 'product-item3.jpg','type' => 'jpg','size' => '2222','product_id' => 3,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 4,'image_url' => 'http://127.0.0.1:8000/uploads/products/product-item4.jpg', 'name' => 'product-item4.jpg','type' => 'jpg','size' => '2222','product_id' => 4,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 5,'image_url' => 'http://127.0.0.1:8000/uploads/products/service-image1.jpg', 'name' => 'service-image1.jpg','type' => 'jpg','size' => '2222','product_id' => 5,'user_id' =>  2, 'created_at' => Carbon::now()]);      
        DB::table('product_images')->insert(['id' => 6,'image_url' => 'http://127.0.0.1:8000/uploads/products/service-image2.jpg', 'name' => 'service-image4.jpg','type' => 'jpg','size' => '2222','product_id' => 6,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 7,'image_url' => 'http://127.0.0.1:8000/uploads/products/service-image3.jpg', 'name' => 'service-image3.jpg','type' => 'jpg','size' => '2222','product_id' => 7,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 8,'image_url' => 'http://127.0.0.1:8000/uploads/products/service-image4.jpg', 'name' => 'service-image4.jpg','type' => 'jpg','size' => '2222','product_id' => 8,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 9,'image_url' => 'http://127.0.0.1:8000/uploads/products/skill-image1.jpg', 'name' => 'skill-image1.jpg','type' => 'jpg','size' => '2222','product_id' => 9,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 10,'image_url' => 'http://127.0.0.1:8000/uploads/products/skill-image2.jpg', 'name' => 'skill-image4.jpg','type' => 'jpg','size' => '2222','product_id' => 10,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 11,'image_url' => 'http://127.0.0.1:8000/uploads/products/skill-image3.jpg', 'name' => 'skill-image3.jpg','type' => 'jpg','size' => '2222','product_id' => 11,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('product_images')->insert(['id' => 12,'image_url' => 'http://127.0.0.1:8000/uploads/products/skill-image4.jpg', 'name' => 'skill-image4.jpg','type' => 'jpg','size' => '2222','product_id' => 12,'user_id' =>  2, 'created_at' => Carbon::now()]);      
       DB::table('products')->insert(['id' => 1,'user_id' => 2,'name' => 'Product 1','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 1,'type_id' => 3,'category_id' => 1453, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 2,'user_id' => 2,'name' => 'Product 2','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 2,'type_id' => 3,'category_id' => 1445, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 3,'user_id' => 2,'name' => 'Product 3','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 3,'type_id' => 3,'category_id' => 1417, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 4,'user_id' => 2,'name' => 'Product 4','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 4,'type_id' => 3,'category_id' => 1519, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 5,'user_id' => 2,'name' => 'Service 1','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 6,'user_id' => 2,'name' => 'Service 2','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 7,'user_id' => 2,'name' => 'Service 3','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 1,'category_id' => 21, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 8,'user_id' => 2,'name' => 'Service 4','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 1,'category_id' => 44, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 9,'user_id' => 2,'name' => 'Skill 1','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 2,'category_id' => 257, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 10,'user_id' => 2,'name' => 'Skill 2','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 2,'category_id' => 322, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 11,'user_id' => 2,'name' => 'Skill 3','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 2,'category_id' => 328, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 12,'user_id' => 2,'name' => 'Skill 4','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 2,'category_id' => 307, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 13,'user_id' => 2,'name' => 'Product 5','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 1,'type_id' => 3,'category_id' => 1453, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 14,'user_id' => 2,'name' => 'Product 6','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 2,'type_id' => 3,'category_id' => 1445, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 15,'user_id' => 2,'name' => 'Product 7','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 3,'type_id' => 3,'category_id' => 1417, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 16,'user_id' => 2,'name' => 'Product 8','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 4,'type_id' => 3,'category_id' => 1519, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 17,'user_id' => 2,'name' => 'Service 5','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 18,'user_id' => 2,'name' => 'Service 6','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 19,'user_id' => 2,'name' => 'Service 7','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 1,'category_id' => 21, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 20,'user_id' => 2,'name' => 'Service 8','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 1,'category_id' => 44, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 21,'user_id' => 2,'name' => 'Skill 5','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 2,'category_id' => 257, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 22,'user_id' => 2,'name' => 'Skill 6','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 2,'category_id' => 322, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 23,'user_id' => 2,'name' => 'Skill 7','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 2,'category_id' => 328, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 24,'user_id' => 2,'name' => 'Skill 8','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 2,'category_id' => 307, 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 1,'buy_id' => null,'sell_id' => 2,'product_id' => 1,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 1', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 2,'buy_id' => null,'sell_id' => 2,'product_id' => 2,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 2', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 3,'buy_id' => null,'sell_id' => 2,'product_id' => 3,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 3', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 4,'buy_id' => null,'sell_id' => 2,'product_id' => 4,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 4', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 5,'buy_id' => null,'sell_id' => 2,'product_id' => 5,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 1', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 6,'buy_id' => null,'sell_id' => 2,'product_id' => 6,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 2', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 7,'buy_id' => null,'sell_id' => 2,'product_id' => 7,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 3', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 8,'buy_id' => null,'sell_id' => 2,'product_id' => 8,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 4', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 9,'buy_id' => null,'sell_id' => 2,'product_id' => 9,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 1', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 10,'buy_id' => null,'sell_id' => 2,'product_id' => 10,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 2', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 11,'buy_id' => null,'sell_id' => 2,'product_id' => 11,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 3', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 12,'buy_id' => null,'sell_id' => 2,'product_id' => 12,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 4', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 13,'buy_id' => null,'sell_id' => 2,'product_id' => 13,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 5', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 14,'buy_id' => null,'sell_id' => 2,'product_id' => 14,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 6', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 15,'buy_id' => null,'sell_id' => 2,'product_id' => 15,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 7', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 16,'buy_id' => null,'sell_id' => 2,'product_id' => 16,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 8', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 17,'buy_id' => null,'sell_id' => 2,'product_id' => 17,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 5', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 18,'buy_id' => null,'sell_id' => 2,'product_id' => 18,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 6', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 19,'buy_id' => null,'sell_id' => 2,'product_id' => 19,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 7', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 20,'buy_id' => null,'sell_id' => 2,'product_id' => 20,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 8', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 21,'buy_id' => null,'sell_id' => 2,'product_id' => 21,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 5', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 22,'buy_id' => null,'sell_id' => 2,'product_id' => 22,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 6', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 23,'buy_id' => null,'sell_id' => 2,'product_id' => 23,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 7', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 24,'buy_id' => null,'sell_id' => 2,'product_id' => 24,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 8', 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 25,'user_id' => 2,'name' => 'Product 9','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 1,'type_id' => 3,'category_id' => 1453, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 26,'user_id' => 2,'name' => 'Product 10','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 2,'type_id' => 3,'category_id' => 1445, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 27,'user_id' => 2,'name' => 'Product 11','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 3,'type_id' => 3,'category_id' => 1417, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 28,'user_id' => 2,'name' => 'Product 12','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 4,'type_id' => 3,'category_id' => 1519, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 29,'user_id' => 2,'name' => 'Service 9','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 30,'user_id' => 2,'name' => 'Service 10','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 31,'user_id' => 2,'name' => 'Service 11','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 1,'category_id' => 21, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 32,'user_id' => 2,'name' => 'Service 12','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 1,'category_id' => 44, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 33,'user_id' => 2,'name' => 'Skill 9','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 2,'category_id' => 257, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 34,'user_id' => 2,'name' => 'Skill 10','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 2,'category_id' => 322, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 35,'user_id' => 2,'name' => 'Skill 11','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 2,'category_id' => 328, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id'=> 36,'user_id' => 2,'name' => 'Skill 12','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 2,'category_id' => 307, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 37,'user_id' => 2,'name' => 'Product 13','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 1,'type_id' => 3,'category_id' => 1453, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 38,'user_id' => 2,'name' => 'Product 14','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 2,'type_id' => 3,'category_id' => 1445, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 39,'user_id' => 2,'name' => 'Product 15','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 3,'type_id' => 3,'category_id' => 1417, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 40,'user_id' => 2,'name' => 'Product 16','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 4,'type_id' => 3,'category_id' => 1519, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 41,'user_id' => 2,'name' => 'Service 13','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 42,'user_id' => 2,'name' => 'Service 14','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 1,'category_id' => 104, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 43,'user_id' => 2,'name' => 'Service 15','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 1,'category_id' => 21, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 44,'user_id' => 2,'name' => 'Service 16','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 1,'category_id' => 44, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 45,'user_id' => 2,'name' => 'Skill 13','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 5,'type_id' => 2,'category_id' => 257, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 46,'user_id' => 2,'name' => 'Skill 14','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 6,'type_id' => 2,'category_id' => 322, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 47,'user_id' => 2,'name' => 'Skill 15','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 7,'type_id' => 2,'category_id' => 328, 'created_at' => Carbon::now()]);
       DB::table('products')->insert(['id' => 48,'user_id' => 2,'name' => 'Skill 16','description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','image_id' => 8,'type_id' => 2,'category_id' => 307, 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 25,'buy_id' => null,'sell_id' => 2,'product_id' => 25,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 9', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 26,'buy_id' => null,'sell_id' => 2,'product_id' => 26,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 10', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 27,'buy_id' => null,'sell_id' => 2,'product_id' => 27,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 11', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 28,'buy_id' => null,'sell_id' => 2,'product_id' => 28,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 12', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 29,'buy_id' => null,'sell_id' => 2,'product_id' => 29,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 9', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 30,'buy_id' => null,'sell_id' => 2,'product_id' => 30,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 10', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 31,'buy_id' => null,'sell_id' => 2,'product_id' => 31,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 11', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 32,'buy_id' => null,'sell_id' => 2,'product_id' => 32,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 12', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 33,'buy_id' => null,'sell_id' => 2,'product_id' => 33,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 9', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 34,'buy_id' => null,'sell_id' => 2,'product_id' => 34,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 10', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 35,'buy_id' => null,'sell_id' => 2,'product_id' => 35,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 11', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 36,'buy_id' => null,'sell_id' => 2,'product_id' => 36,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 12', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 37,'buy_id' => null,'sell_id' => 2,'product_id' => 37,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 13', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 38,'buy_id' => null,'sell_id' => 2,'product_id' => 38,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 14', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 39,'buy_id' => null,'sell_id' => 2,'product_id' => 39,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 15', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 40,'buy_id' => null,'sell_id' => 2,'product_id' => 40,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Product 16', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 41,'buy_id' => null,'sell_id' => 2,'product_id' => 41,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 13', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 42,'buy_id' => null,'sell_id' => 2,'product_id' => 42,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 14', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 43,'buy_id' => null,'sell_id' => 2,'product_id' => 43,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 15', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 44,'buy_id' => null,'sell_id' => 2,'product_id' => 44,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Service 16', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 45,'buy_id' => null,'sell_id' => 2,'product_id' => 45,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 13', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 46,'buy_id' => null,'sell_id' => 2,'product_id' => 46,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 14', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 47,'buy_id' => null,'sell_id' => 2,'product_id' => 47,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 15', 'created_at' => Carbon::now()]);
       DB::table('traddes')->insert(['id' => 48,'buy_id' => null,'sell_id' => 2,'product_id' => 48,'amount' => 22.62,'status' => 1,'item_description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!','tradde_number' => null,'title' => 'Skill 16', 'created_at' => Carbon::now()]);
    




    }
}
