<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class ServicesSeeder extends Seeder
{
    /** 'created_at' => Carbon::now()
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->where('id','=', 1)->delete();
        DB::table('categories')->where('id','=', 2)->delete();
        DB::table('categories')->where('id','=', 3)->delete();
        DB::table('categories')->where('id','=', 4)->delete();
        DB::table('categories')->where('id','=', 5)->delete();
        DB::table('categories')->where('id','=', 6)->delete();
        DB::table('categories')->where('id','=', 7)->delete();
        DB::table('categories')->where('id','=', 8)->delete();
        DB::table('categories')->where('id','=', 9)->delete();
        DB::table('categories')->where('id','=', 10)->delete();
        DB::table('categories')->where('id','=', 11)->delete();
        DB::table('categories')->where('id','=', 12)->delete();
        DB::table('categories')->where('id','=', 13)->delete();
        DB::table('categories')->where('id','=', 14)->delete();
        DB::table('categories')->where('id','=', 15)->delete();
        DB::table('categories')->where('id','=', 16)->delete();
        DB::table('categories')->where('id','=', 17)->delete();
        DB::table('categories')->where('id','=', 18)->delete();
        DB::table('categories')->where('id','=', 19)->delete();
        DB::table('categories')->where('id','=', 20)->delete();
        DB::table('categories')->where('id','=', 21)->delete();
        DB::table('categories')->where('id','=', 22)->delete();
        DB::table('categories')->where('id','=', 23)->delete();
        DB::table('categories')->where('id','=', 24)->delete();
        DB::table('categories')->where('id','=', 25)->delete();
        DB::table('categories')->where('id','=', 26)->delete();
        DB::table('categories')->where('id','=', 27)->delete();
        DB::table('categories')->where('id','=', 28)->delete();
        DB::table('categories')->where('id','=', 29)->delete();
        DB::table('categories')->where('id','=', 30)->delete();
        DB::table('categories')->where('id','=', 31)->delete();
        DB::table('categories')->where('id','=', 32)->delete();
        DB::table('categories')->where('id','=', 33)->delete();
        DB::table('categories')->where('id','=', 34)->delete();
        DB::table('categories')->where('id','=', 35)->delete();
        DB::table('categories')->where('id','=', 36)->delete();
        DB::table('categories')->where('id','=', 37)->delete();
        DB::table('categories')->where('id','=', 38)->delete();
        DB::table('categories')->where('id','=', 39)->delete();
        DB::table('categories')->where('id','=', 40)->delete();
        DB::table('categories')->where('id','=', 41)->delete();
        DB::table('categories')->where('id','=', 42)->delete();
        DB::table('categories')->where('id','=', 43)->delete();
        DB::table('categories')->where('id','=', 44)->delete();
        DB::table('categories')->where('id','=', 45)->delete();
        DB::table('categories')->where('id','=', 46)->delete();
        DB::table('categories')->where('id','=', 47)->delete();
        DB::table('categories')->where('id','=', 48)->delete();
        DB::table('categories')->where('id','=', 49)->delete();
        DB::table('categories')->where('id','=', 50)->delete();
        DB::table('categories')->where('id','=', 51)->delete();
        DB::table('categories')->where('id','=', 52)->delete();
        DB::table('categories')->where('id','=', 53)->delete();
        DB::table('categories')->where('id','=', 54)->delete();
        DB::table('categories')->where('id','=', 55)->delete();
        DB::table('categories')->where('id','=', 56)->delete();
        DB::table('categories')->where('id','=', 57)->delete();
        DB::table('categories')->where('id','=', 58)->delete();
        DB::table('categories')->where('id','=', 59)->delete();
        DB::table('categories')->where('id','=', 60)->delete();
        DB::table('categories')->where('id','=', 61)->delete();
        DB::table('categories')->where('id','=', 62)->delete();
        DB::table('categories')->where('id','=', 63)->delete();
        DB::table('categories')->where('id','=', 64)->delete();
        DB::table('categories')->where('id','=', 65)->delete();
        DB::table('categories')->where('id','=', 66)->delete();
        DB::table('categories')->where('id','=', 67)->delete();
        DB::table('categories')->where('id','=', 68)->delete();
        DB::table('categories')->where('id','=', 69)->delete();
        DB::table('categories')->where('id','=', 70)->delete();
        DB::table('categories')->where('id','=', 71)->delete();
        DB::table('categories')->where('id','=', 72)->delete();
        DB::table('categories')->where('id','=', 73)->delete();
        DB::table('categories')->where('id','=', 74)->delete();
        DB::table('categories')->where('id','=', 75)->delete();
        DB::table('categories')->where('id','=', 76)->delete();
        DB::table('categories')->where('id','=', 77)->delete();
        DB::table('categories')->where('id','=', 78)->delete();
        DB::table('categories')->where('id','=', 79)->delete();
        DB::table('categories')->where('id','=', 80)->delete();
        DB::table('categories')->where('id','=', 81)->delete();
        DB::table('categories')->where('id','=', 82)->delete();
        DB::table('categories')->where('id','=', 83)->delete();
        DB::table('categories')->where('id','=', 84)->delete();
        DB::table('categories')->where('id','=', 85)->delete();
        DB::table('categories')->where('id','=', 86)->delete();
        DB::table('categories')->where('id','=', 87)->delete();
        DB::table('categories')->where('id','=', 88)->delete();
        DB::table('categories')->where('id','=', 89)->delete();
        DB::table('categories')->where('id','=', 90)->delete();
        DB::table('categories')->where('id','=', 91)->delete();
        DB::table('categories')->where('id','=', 92)->delete();
        DB::table('categories')->where('id','=', 93)->delete();
        DB::table('categories')->where('id','=', 94)->delete();
        DB::table('categories')->where('id','=', 95)->delete();
        DB::table('categories')->where('id','=', 96)->delete();
        DB::table('categories')->where('id','=', 97)->delete();
        DB::table('categories')->where('id','=', 98)->delete();
        DB::table('categories')->where('id','=', 99)->delete();
        DB::table('categories')->where('id','=', 100)->delete();
        DB::table('categories')->where('id','=', 101)->delete();
        DB::table('categories')->where('id','=', 102)->delete();
        DB::table('categories')->where('id','=', 103)->delete();
        DB::table('categories')->where('id','=', 104)->delete();
        DB::table('categories')->where('id','=', 105)->delete();
        DB::table('categories')->where('id','=', 106)->delete();
        DB::table('categories')->where('id','=', 107)->delete();
        DB::table('categories')->where('id','=', 108)->delete();
        DB::table('categories')->where('id','=', 109)->delete();
        DB::table('categories')->where('id','=', 110)->delete();
        DB::table('categories')->where('id','=', 111)->delete();
        DB::table('categories')->where('id','=', 112)->delete();
        DB::table('categories')->where('id','=', 113)->delete();
        DB::table('categories')->where('id','=', 114)->delete();
        DB::table('categories')->where('id','=', 115)->delete();
        DB::table('categories')->where('id','=', 116)->delete();
        DB::table('categories')->where('id','=', 117)->delete();
        DB::table('categories')->where('id','=', 118)->delete();
        DB::table('categories')->where('id','=', 119)->delete();
        DB::table('categories')->where('id','=', 120)->delete();
        DB::table('categories')->where('id','=', 121)->delete();
        DB::table('categories')->where('id','=', 122)->delete();
        DB::table('categories')->where('id','=', 123)->delete();
        DB::table('categories')->where('id','=', 124)->delete();
        DB::table('categories')->where('id','=', 125)->delete();
        DB::table('categories')->where('id','=', 126)->delete();
        DB::table('categories')->where('id','=', 127)->delete();
        DB::table('categories')->where('id','=', 128)->delete();
        DB::table('categories')->where('id','=', 129)->delete();
        DB::table('categories')->where('id','=', 130)->delete();
        DB::table('categories')->where('id','=', 131)->delete();
        DB::table('categories')->where('id','=', 132)->delete();
        DB::table('categories')->where('id','=', 133)->delete();
        DB::table('categories')->where('id','=', 134)->delete();
        DB::table('categories')->where('id','=', 135)->delete();
        DB::table('categories')->where('id','=', 136)->delete();
        DB::table('categories')->where('id','=', 137)->delete();
        DB::table('categories')->where('id','=', 138)->delete();
        DB::table('categories')->where('id','=', 139)->delete();
        DB::table('categories')->where('id','=', 140)->delete();
        DB::table('categories')->where('id','=', 141)->delete();
        DB::table('categories')->where('id','=', 142)->delete();
        DB::table('categories')->where('id','=', 143)->delete();
        DB::table('categories')->where('id','=', 144)->delete();
        DB::table('categories')->where('id','=', 145)->delete();
        DB::table('categories')->where('id','=', 146)->delete();
        DB::table('categories')->where('id','=', 147)->delete();
        DB::table('categories')->where('id','=', 148)->delete();
        DB::table('categories')->where('id','=', 149)->delete();
        DB::table('categories')->where('id','=', 150)->delete();
        DB::table('categories')->where('id','=', 151)->delete();
        DB::table('categories')->where('id','=', 152)->delete();
        DB::table('categories')->where('id','=', 153)->delete();
        DB::table('categories')->where('id','=', 154)->delete();
        DB::table('categories')->where('id','=', 155)->delete();
        DB::table('categories')->where('id','=', 156)->delete();
        DB::table('categories')->where('id','=', 157)->delete();
        DB::table('categories')->where('id','=', 158)->delete();
        DB::table('categories')->where('id','=', 159)->delete();
        DB::table('categories')->where('id','=', 160)->delete();
        DB::table('categories')->where('id','=', 161)->delete();
        DB::table('categories')->where('id','=', 162)->delete();
        DB::table('categories')->where('id','=', 163)->delete();
        DB::table('categories')->where('id','=', 164)->delete();
        DB::table('categories')->where('id','=', 165)->delete();
        DB::table('categories')->where('id','=', 166)->delete();
        DB::table('categories')->where('id','=', 167)->delete();
        DB::table('categories')->where('id','=', 168)->delete();
        DB::table('categories')->where('id','=', 169)->delete();
        DB::table('categories')->where('id','=', 170)->delete();
        DB::table('categories')->where('id','=', 171)->delete();
        DB::table('categories')->where('id','=', 172)->delete();
        DB::table('categories')->where('id','=', 173)->delete();
        DB::table('categories')->where('id','=', 174)->delete();
        DB::table('categories')->where('id','=', 175)->delete();
        DB::table('categories')->where('id','=', 176)->delete();
        DB::table('categories')->where('id','=', 177)->delete();
        DB::table('categories')->where('id','=', 178)->delete();
        DB::table('categories')->where('id','=', 179)->delete();
        DB::table('categories')->where('id','=', 180)->delete();
        DB::table('categories')->where('id','=', 181)->delete();
        DB::table('categories')->where('id','=', 182)->delete();
        DB::table('categories')->where('id','=', 183)->delete();
        DB::table('categories')->where('id','=', 184)->delete();
        DB::table('categories')->where('id','=', 185)->delete();
        DB::table('categories')->where('id','=', 186)->delete();
        DB::table('categories')->where('id','=', 187)->delete();
        DB::table('categories')->where('id','=', 188)->delete();
        DB::table('categories')->where('id','=', 189)->delete();
        DB::table('categories')->where('id','=', 190)->delete();
        DB::table('categories')->where('id','=', 191)->delete();
        DB::table('categories')->where('id','=', 192)->delete();
        DB::table('categories')->where('id','=', 193)->delete();
        DB::table('categories')->where('id','=', 194)->delete();
        DB::table('categories')->where('id','=', 195)->delete();
        DB::table('categories')->where('id','=', 196)->delete();
        DB::table('categories')->where('id','=', 197)->delete();
        DB::table('categories')->where('id','=', 198)->delete();
        DB::table('categories')->where('id','=', 199)->delete();
        DB::table('categories')->where('id','=', 200)->delete();
        DB::table('categories')->where('id','=', 201)->delete();
        DB::table('categories')->where('id','=', 202)->delete();
        DB::table('categories')->where('id','=', 203)->delete();
        DB::table('categories')->where('id','=', 204)->delete();
        DB::table('categories')->where('id','=', 205)->delete();
        DB::table('categories')->where('id','=', 206)->delete();
        DB::table('categories')->where('id','=', 207)->delete();
        DB::table('categories')->where('id','=', 208)->delete();
        DB::table('categories')->where('id','=', 209)->delete();
        DB::table('categories')->where('id','=', 210)->delete();
        DB::table('categories')->where('id','=', 211)->delete();
        DB::table('categories')->where('id','=', 212)->delete();
        DB::table('categories')->where('id','=', 213)->delete();
        DB::table('categories')->where('id','=', 214)->delete();
        DB::table('categories')->where('id','=', 215)->delete();
        DB::table('categories')->where('id','=', 216)->delete();
        DB::table('categories')->where('id','=', 217)->delete();
        DB::table('categories')->where('id','=', 218)->delete();
        DB::table('categories')->where('id','=', 219)->delete();
        DB::table('categories')->where('id','=', 220)->delete();
        DB::table('categories')->where('id','=', 221)->delete();
        DB::table('categories')->where('id','=', 222)->delete();
        DB::table('categories')->where('id','=', 223)->delete();
        DB::table('categories')->where('id','=', 224)->delete();
        DB::table('categories')->where('id','=', 225)->delete();
        DB::table('categories')->where('id','=', 226)->delete();
        DB::table('categories')->where('id','=', 227)->delete();
        DB::table('categories')->where('id','=', 228)->delete();
        DB::table('categories')->where('id','=', 229)->delete();
        DB::table('categories')->where('id','=', 230)->delete();
        DB::table('categories')->where('id','=', 231)->delete();
        DB::table('categories')->where('id','=', 232)->delete();
        DB::table('categories')->where('id','=', 233)->delete();
        DB::table('categories')->where('id','=', 234)->delete();
        DB::table('categories')->where('id','=', 235)->delete();
        DB::table('categories')->where('id','=', 236)->delete();
        DB::table('categories')->where('id','=', 237)->delete();
        DB::table('categories')->where('id','=', 238)->delete();
        DB::table('categories')->where('id','=', 239)->delete();
        DB::table('categories')->where('id','=', 240)->delete();
        DB::table('categories')->where('id','=', 241)->delete();
        DB::table('categories')->where('id','=', 242)->delete();
        DB::table('categories')->where('id','=', 243)->delete();
        DB::table('categories')->where('id','=', 244)->delete();
        DB::table('categories')->where('id','=', 245)->delete();
        DB::table('categories')->where('id','=', 246)->delete();
        DB::table('categories')->where('id','=', 247)->delete();
        DB::table('categories')->where('id','=', 248)->delete();
        DB::table('categories')->where('id','=', 249)->delete();
        DB::table('categories')->where('id','=', 250)->delete();
        DB::table('categories')->where('id','=', 251)->delete();
        DB::table('categories')->where('id','=', 252)->delete();
        DB::table('categories')->where('id','=', 253)->delete();
        DB::table('categories')->where('id','=', 254)->delete();
        DB::table('categories')->where('id','=', 255)->delete();
        DB::table('categories')->where('id','=', 256)->delete();
        DB::table('categories')->insert(['id' =>1799,
        'name' => 'Academic Consulting Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1800,
        'name' => 'Administrative Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1801,
        'name' => 'Animal Care Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1802,
        'name' => 'Automobile Maintenance and Repair',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1803,
        'name' => 'Beauty and Lifestyle Service Business',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1804,
        'name' => 'Elder Care Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1805,
        'name' => 'Event Service Businesses',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1806,
        'name' => 'Home Maintenance and Repair Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1807,
        'name' => 'Legal Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1808,
        'name' => 'Personal Concierge Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1809,
        'name' => 'Personal Health and Wellness Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1810,
        'name' => 'Sales and Marketing',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1811,
        'name' => 'Serving Parents Babies and Small Children',
        'parent' =>  1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1812,
        'name' => 'Technology Maintenance and Repair Services',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['id' =>1813,
        'name' => 'Travel and Tourism Service Businesses',
        'parent' => 1329,
        'type_id'=> 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Private School Application Consultant',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Homeschool Teacher',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Academic Tutoring',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Online English Tutor',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'SAT Tutoring and Preparation',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'GED Test Preparation',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'College Application Consultant',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'College Essay Editor',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Cover Letter and Resume Writer',
        'parent' => 1799,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Virtual Assistant',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Executive Headhunting',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Language Translation',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Project Manager',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Book-keeping',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Certified Professional Accountant',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Payroll Processing Service',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Financial Auditor',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Business Plan Consultant',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Office Support Services',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Data Analysis',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Messenger Service',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Online Course Consultant',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Freelance Researcher',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Online Business Coach',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Customer Service Phone Operator',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Live Chat Customer Support Service',
        'parent' => 1800,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Pet Sitting',
        'parent' => 1801,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Dog Walking',
        'parent' => 1801,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Mobile Veterinary Services',
        'parent' => 1801,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Mobile Pet Grooming',
        'parent' => 1801,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Mobile Car Wash and Car Detailing',
        'parent' => 1802,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Mobile Car Mechanic',
        'parent' => 1802,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Vehicle Inspection Service',
        'parent' => 1802,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Windshield Repair Service',
        'parent' => 1802,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Makeup Artist',
        'parent' => 1803,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'In-Home Hair Stylist, Hairdressers, hairstylists, and cosmetologists',
        'parent' => 1803,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Personal Wardrobe Stylist',
        'parent' => 1803,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Life Coach',
        'parent' => 1803,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Online Dating Consultant / Profile Editor',
        'parent' => 1803,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Elder Companion and Care Provider',
        'parent' => 1804,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'In-Home Physical Therapist',
        'parent' => 1804,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Private Nursing Service',
        'parent' => 1804,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Corporate Event Planner',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Fundraising Event Coordinator',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Trade Show Producer',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Wedding Planner',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Conference Marketing Manager',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Event Photographer',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Event Videographer',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Audio Visual Technician',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Lighting Designer',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Live Video Producer',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Event Catering Services',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Custom Baking',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Photo Booth Rental Service',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Reunion Coordinator',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Valet Parking Service',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Event Furniture and Equipment Rental',
        'parent' => 1805,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Handyman Service',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Pool Servicing and Maintenance',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Lawn Care',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Locksmith Services',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Home Entertainment Installation',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Home-Inspection Services',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Interior Painting Service',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Wallpaper Installation Service',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Power Washing Service',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Carpet Installation Service',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Air Conditioning Installation and Maintenance',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Plumbing Service',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Appliance Repair',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Porcelain Repair',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Home Maintenance Equipment Rental',
        'parent' => 1806,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Mobile Notary Public',
        'parent' => 1807,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Legal Process Server',
        'parent' => 1807,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Paralegal Services',
        'parent' => 1807,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Private Investigator',
        'parent' => 1807,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Contract Drafting and Review Service',
        'parent' => 1807,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Grocery Shopping and Delivery',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Errand Runner',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Dry-Cleaning Delivery and Pick-Up',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Seamstress or Tailor Services',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Window Washing',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Home Cleaning Service',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Private Car Service',
        'parent' => 1808,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Personal Fitness Trainer',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Meditation Instructor',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Private Yoga Instructor',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'In-Home Masseuse',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Acupuncturist',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Chiropractor',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Nutrition Consultant',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Meal Delivery Service',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Personal Chef',
        'parent' => 1809,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Graphic Designer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Website Designer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Marketing Copywriter',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Content Writer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Editing and Proofreading Service',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Ebook Ghostwriter',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Facebook Ads Strategist',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Instagram Marketing Strategist',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Social Media Manager',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Content Marketing Strategist',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'SEO Strategist',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Email Marketing Manager',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Affiliate Sales and Marketing Consultant',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Brand Photographer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Marketing Video Producer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Podcast Producer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Presentation and Proposal Designer',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Public Relations Consultant',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Brand Ambassador',
        'parent' => 1810,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Doula and Birth Coaching Services',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Birth Photographer',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Overnight Doula Service',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Lactation Consultant',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'On-Demand Babysitter',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Home Baby Proofing Consultant',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Nanny and Au Pair Placement Service',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Private Music Teacher',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Children’s Party Planner',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Birthday Party Character Appearances',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Children’s Entertainment Services',
        'parent' => 1811,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'IT Systems Consultant',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Computer Repair Service',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Printer and Copy Machine Maintenance',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Software Installation Service',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Mobile IT Support Service',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'App Developer',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Online Network Installation and Maintenance',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Online Security Consultant',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Data Management Consultant',
        'parent' => 1812,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Rental Property Management',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Local Tour Guide',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Adventure Tours',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Travel Agent',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Corporate Retreat Coordinator',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Cruise Booking Agent',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Travel Concierge Services',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Ski or Snowboarding Instructor',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'SCUBA Diving Instructor',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);
        DB::table('categories')->insert(['name' => 'Beach Equipment Rentals',
        'parent' => 1813,
        'type_id' => 1,
        'created_at' => Carbon::now()]);

    }
}
